#!/usr/bin/env python

# This is an motioneye action button script for a sg90 micro servo pan/tilt like this one: https://www.thingiverse.com/thing:708819
# You may need to figure out your own MIN / MAX range
# This script will put everything back to center in case something gets bumped or out of sync

import time
import sys
import pigpio
if sys.version > '3':
   buffer = memoryview

PAN=13 # Pan servo gpio.
TILT=18 # Tilt servo gpio.

PAN_MIN=650.0
PAN_MAX=2250.0
PAN_MID=1575

TILT_MIN=900.0
TILT_MAX=2250.0
TILT_MID=1700

pan_pos=PAN_MID
tilt_pos=TILT_MID

RUNTIME=0.3

pi=pigpio.pi() # Connect to local Pi.

start_time = time.time()

while (time.time()-start_time) < RUNTIME:

   pi.set_servo_pulsewidth(PAN, pan_pos)

   with open('/etc/motioneye/pan_pos', 'w') as f:
       new_pan_pos = int(pan_pos)
       record_new_pos = str(new_pan_pos) 
       f.write(record_new_pos)
       f.close()

   pi.set_servo_pulsewidth(TILT, tilt_pos)

   with open('/etc/motioneye/tilt_pos', 'w') as f:
       new_tilt_pos = int(tilt_pos)
       record_new_pos = str(new_tilt_pos) 
       f.write(record_new_pos)
       f.close()

   time.sleep(0.05) # Nominal 20 updates per second.

pi.stop() # Disconnect from local Pi.
